# Generated by Django 3.1.7 on 2021-04-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='date',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='table',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='table',
            name='phone',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='table',
            name='time',
            field=models.CharField(max_length=40),
        ),
    ]
