# Generated by Django 3.1.7 on 2021-04-07 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media')),
                ('category', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
